name = "TextSearch"
uuid = "7f6f6c8a-3b03-11e9-223d-e7d88259bd6c"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.9.5"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KCenters = "5d8de97f-65f8-4dd6-a15b-0f89c36a43ce"
KNearestCenters = "4dca28ae-43b8-11eb-1f5e-d55054101997"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
CategoricalArrays = "0.8, 0.9, 0.10"
JSON3 = "1.5"
KCenters = "0.4"
KNearestCenters = "0.5"
SimilaritySearch = "0.4, 0.5"
StatsBase = "0.32.0, 0.33"
StructTypes = "1.2"
julia = "1.3"
