name = "TextSearch"
uuid = "7f6f6c8a-3b03-11e9-223d-e7d88259bd6c"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.3.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
DataStructures = "0.17"
GZip = "0.5.0"
JSON = "0.19.0, 0.21.0"
SimilaritySearch = "0.3.11"
StatsBase = "0.30.0, 0.32.0"
julia = "0.7, 1"
